# Configuration principale du site Jekyll

title: ENSIIE FIPA
email: tonemail@example.com
description: >-
  Cours, TP et TD de la formation FISA de l'ENSIIE.
baseurl: "" # Utilise "/nom-du-repo" si tu déploies sur GitHub Pages avec un repo
url: "https://ensii-fipa.github.io"
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Source des fichiers markdown (docs/)
source: docs

# Inclure le dossier docs (même s'il est source, c'est parfois nécessaire)
include:
  - docs

# Collections personnalisées
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Options Markdown et coloration syntaxique
markdown: kramdown
highlighter: rouge

# Défauts pour les documents de type "docs"
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"
